# LAMP docker compose file for COMP4039-DIS Coursework 2
# The 'version' field is no longer required in Docker Compose files version 3.9 and above. see https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete.
# version: '3'

services:
  php-apache:
    #image: php:8.1-apache
    build:
      context: ./php-apache
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
    links:
      - mariadb
    restart: always

  mariadb:
    #image: mariadb:10.8
    build: 
      context: ./mariadb
    restart: always
    ports:
      - 3306
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      TZ: "Europe/London"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpwd
    ports:
      - 8081:80

        #volumes:
        #    mariadb-data:
